/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FxContract =
  | SourceQuote
  | QuoteSnapshot
  | EstimateRequest
  | EstimateResult
  | SelectionContext
  | DerivedCrossQuote
  | ObjectReference
  | Provider
  | ProviderSnapshot
  | ReleaseManifest
  | CurrentRelease
  | DerivedEstimateResult;

export interface SourceQuote {
  providerId: string;
  subjectCurrency: string;
  priceCurrency: string;
  unitAmount: string;
  buy: string | null;
  sell: string | null;
  sourcePublishedAt: string | null;
  fetchedAt: string;
  lastSuccessfulCheckAt: string;
  serviceCountry: string;
  deliveryMethod: 'cash' | 'account';
  channel: 'branch' | 'online' | 'atm' | 'unknown';
  branchId?: string;
  /**
   * @maxItems 100
   */
  denominations?: string[];
  amountRange?: {
    currency: string;
    min: string;
    max: string;
  };
  /**
   * @maxItems 100
   */
  qualifications?: string[];
  feeStatus?: 'unknown' | 'no_additional_fee' | 'unsupported';
  sourceUrl?: string;
  originalBuyField?: string;
  originalSellField?: string;
  mappingVersion?: string;
  originalUnitAmount?: string;
  dataKind?: 'published_board' | 'fixed_fallback' | 'reference' | 'derived_cross';
  feeEvidenceUrl?: string;
}
export interface QuoteSnapshot {
  quoteId: string;
  quoteSeriesId: string;
  providerId: string;
  fromCurrency: string;
  toCurrency: string;
  providerSide: 'buy' | 'sell';
  status: 'available' | 'unavailable';
  rate: string | null;
  unavailableReason: 'not_quoted' | null;
  sourceQuote: SourceQuote;
  methodVersion: '1';
}
export interface EstimateRequest {
  fromCurrency: string;
  toCurrency: string;
  amount: string;
  mode: 'EXACT_IN' | 'EXACT_OUT';
}
export interface EstimateResult {
  status: 'available' | 'unavailable';
  fromAmount: string | null;
  toAmount: string | null;
  quoteId: string | null;
  rate: string | null;
  reason: string | null;
  feeStatus: 'unknown' | 'no_additional_fee' | 'unsupported';
}
export interface SelectionContext {
  now: string;
  country: string;
  deliveryMethod: 'cash' | 'account';
  channel: 'branch' | 'online' | 'atm' | 'unknown';
  branchId?: string;
  denomination?: string;
  qualifications?: string[];
}
export interface DerivedCrossQuote {
  kind: 'derived_cross';
  providerId: string;
  fromCurrency: string;
  toCurrency: string;
  rate: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  legs: [string, string];
  recommendable: false;
}
export interface ObjectReference {
  path: string;
  sha256: string;
}
export interface Provider {
  providerId: string;
  kind: 'bank' | 'exchange_shop';
  name: string;
  sourceUrl: string;
  /**
   * @minItems 1
   */
  serviceCountries: [string, ...string[]];
  termsUrl: string | null;
  redistributionStatus: 'verified' | 'unknown' | 'restricted';
  attribution: string;
}
export interface ProviderSnapshot {
  schemaVersion: '3.0';
  providerId: string;
  /**
   * @minItems 1
   * @maxItems 10000
   */
  quotes: [QuoteSnapshot, ...QuoteSnapshot[]];
}
export interface ReleaseManifest {
  schemaVersion: '3.0';
  generatedAt: string;
  /**
   * @maxItems 1000
   */
  providers: {
    providerId: string;
    snapshot: ObjectReference;
    checkStatus: 'ok' | 'failed' | 'carried_forward';
    lastSuccessfulCheckAt: string;
  }[];
  /**
   * @maxItems 100000
   */
  history: {
    providerId: string;
    date: string;
    snapshot: ObjectReference;
  }[];
  deprecation: {
    activatedAt: string | null;
    sunsetAt: string | null;
    replacement: string;
  };
}
export interface CurrentRelease {
  schemaVersion: '3.0';
  releaseId: string;
  manifest: ObjectReference;
}
export interface DerivedEstimateResult {
  status: 'available' | 'unavailable';
  fromAmount: string | null;
  toAmount: string | null;
  quoteId: string | null;
  rate: string | null;
  reason: string | null;
  feeStatus: 'unknown' | 'no_additional_fee' | 'unsupported';
  kind: 'derived_cross';
  /**
   * @maxItems 2
   */
  legs: [] | [string] | [string, string];
  recommendable: false;
}
