#!/usr/bin/env node
/**
 * generate-version.js - 自動生成版本號到 .env.local
 *
 * 功能：
 * 1. 從 package.json 讀取基礎版本號
 * 2. 從 Git 獲取 commit hash 和 dirty 狀態
 * 3. 生成完整版本號並寫入 .env.local
 * 4. 確保 Vite 可以讀取 VITE_APP_VERSION 和 VITE_BUILD_TIME
 *
 * 參考: https://vitejs.dev/guide/env-and-mode.html
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * 生成版本號
 * 格式: <package.version>+sha.<git-hash>[-dirty]
 */
function generateVersion() {
  try {
    // 讀取 package.json 版本
    const packagePath = resolve(__dirname, '../package.json');
    const pkg = JSON.parse(readFileSync(packagePath, 'utf-8'));
    const baseVersion = pkg.version;

    // 獲取 Git commit hash
    const commitHash = execSync('git rev-parse --short HEAD', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore'],
    }).trim();

    // 檢查是否有未提交的變更
    const isDirty =
      execSync('git status --porcelain', {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'ignore'],
      }).trim().length > 0;

    // 組合版本號
    const version = `${baseVersion}+sha.${commitHash}${isDirty ? '-dirty' : ''}`;

    return version;
  } catch (error) {
    console.warn('[版本生成] Git 不可用，使用 package.json 版本');
    const packagePath = resolve(__dirname, '../package.json');
    const pkg = JSON.parse(readFileSync(packagePath, 'utf-8'));
    return pkg.version;
  }
}

/**
 * 生成建置時間
 */
function generateBuildTime() {
  return new Date().toISOString();
}

/**
 * 主函數
 */
function main() {
  const version = generateVersion();
  const buildTime = generateBuildTime();

  console.log(`[版本生成] 版本號: ${version}`);
  console.log(`[版本生成] 建置時間: ${buildTime}`);

  // 生成 .env.local 內容
  const envContent = `# 自動生成 - 請勿手動編輯
# Generated by scripts/generate-version.js
# Timestamp: ${buildTime}

VITE_APP_VERSION=${version}
VITE_BUILD_TIME=${buildTime}
`;

  // 寫入 .env.local
  const envPath = resolve(__dirname, '../.env.local');
  writeFileSync(envPath, envContent, 'utf-8');

  console.log(`[版本生成] ✅ 已寫入 .env.local`);
}

main();
