# GitHub Sponsors configuration
# https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

# Optional: Custom link for sponsorship
# custom: ["https://buymeacoffee.com/haotool"]
