/**
 * 情境初始狀態：Cold & Dark 從停機位全斷電開始；Quick / Demo 於 27 跑道頭對正、系統全開、航路已輸入。
 */
import { Quaternion, Vector3 } from 'three';
import { AIRCRAFT, AIRPORT, DEFAULT_CRZ_FL, DEFAULT_ROUTE, DEG } from './constants';
import type {
  DuId,
  EfisState,
  EngineState,
  McduState,
  Scenario,
  SimState,
  WeatherPreset,
  WeatherState,
} from './types';

export const WEATHER_PRESETS: Record<WeatherPreset, Partial<WeatherState>> = {
  CLEAR: {
    windDir: 260,
    windSpeed: 6,
    windAloftDir: 280,
    windAloftSpeed: 25,
    gust: 0,
    turbulence: 0.05,
    visibility: 40000,
    cloudCover: 0.08,
    cloudBase: 5500,
    cloudTop: 7000,
    precipitation: 0,
  },
  SCATTERED: {
    windDir: 250,
    windSpeed: 9,
    windAloftDir: 270,
    windAloftSpeed: 35,
    gust: 4,
    turbulence: 0.15,
    visibility: 30000,
    cloudCover: 0.45,
    cloudBase: 3200,
    cloudTop: 6500,
    precipitation: 0,
  },
  OVERCAST: {
    windDir: 240,
    windSpeed: 12,
    windAloftDir: 260,
    windAloftSpeed: 40,
    gust: 6,
    turbulence: 0.2,
    visibility: 12000,
    cloudCover: 0.95,
    cloudBase: 2200,
    cloudTop: 7800,
    precipitation: 0,
  },
  RAIN: {
    windDir: 230,
    windSpeed: 14,
    windAloftDir: 250,
    windAloftSpeed: 45,
    gust: 10,
    turbulence: 0.35,
    visibility: 5000,
    cloudCover: 1,
    cloudBase: 1400,
    cloudTop: 9000,
    precipitation: 0.85,
    isaDev: -4,
  },
  FOG: {
    windDir: 270,
    windSpeed: 2,
    windAloftDir: 280,
    windAloftSpeed: 12,
    gust: 0,
    turbulence: 0,
    visibility: 550,
    cloudCover: 0.7,
    cloudBase: 300,
    cloudTop: 900,
    precipitation: 0,
  },
  CROSSWIND: {
    windDir: 200,
    windSpeed: 22,
    windAloftDir: 210,
    windAloftSpeed: 50,
    gust: 12,
    turbulence: 0.3,
    visibility: 30000,
    cloudCover: 0.3,
    cloudBase: 4000,
    cloudTop: 6000,
    precipitation: 0,
  },
  TURBULENCE: {
    windDir: 250,
    windSpeed: 15,
    windAloftDir: 270,
    windAloftSpeed: 55,
    gust: 10,
    turbulence: 0.8,
    visibility: 20000,
    cloudCover: 0.55,
    cloudBase: 3500,
    cloudTop: 11000,
    precipitation: 0.1,
  },
  CUSTOM: {},
};

function makeWeather(preset: WeatherPreset, timeOfDay: number): WeatherState {
  return {
    preset,
    windDir: 260,
    windSpeed: 6,
    windAloftDir: 280,
    windAloftSpeed: 25,
    gust: 0,
    turbulence: 0.05,
    visibility: 40000,
    cloudCover: 0.1,
    cloudBase: 5500,
    cloudTop: 7000,
    precipitation: 0,
    isaDev: 0,
    qnh: 1013,
    timeOfDay,
    seed: 7,
    inCloud: false,
    cloudDensityAtAircraft: 0,
    icing: false,
    lightning: 0,
    ...WEATHER_PRESETS[preset],
  };
}

function makeEngine(running: boolean): EngineState {
  return {
    state: running ? 'IDLE' : 'OFF',
    master: running,
    firePushed: false,
    n1: running ? 19.5 : 0,
    n2: running ? 58.5 : 0,
    egt: running ? 420 : 15,
    ff: running ? 300 : 0,
    thrust: 0,
    n1Cmd: running ? 19.5 : 0,
    tla: 0,
    reverser: 0,
    starterValve: false,
    ignition: false,
    fuelValve: running,
    oilPress: running ? 55 : 0,
    startTimer: 0,
    fanAngle: 0,
    bleedPress: running ? 32 : 0,
    antiIce: false,
  };
}

function makeEfis(): EfisState {
  return {
    fd: true,
    ls: false,
    cstr: true,
    wpt: false,
    vord: false,
    ndb: false,
    arpt: true,
    mode: 'ARC',
    range: 20,
    baroStd: false,
    qnh: 1013,
    baroUnit: 'hPa',
  };
}

function makeMcdu(): McduState {
  return {
    page: 'FPLN',
    perfPage: 'TO',
    scratchpad: '',
    message: null,
    scroll: 0,
    msgAmber: false,
    keyFlash: 0,
  };
}

export function headingToQuaternion(headingDeg: number, pitchDeg = 0, rollDeg = 0): Quaternion {
  // 機體 -Z 為機鼻；yaw 繞 +Y 正角使機鼻向左 → 航向需取負
  const q = new Quaternion();
  const yaw = new Quaternion().setFromAxisAngle(new Vector3(0, 1, 0), -headingDeg * DEG);
  const pitch = new Quaternion().setFromAxisAngle(new Vector3(1, 0, 0), pitchDeg * DEG);
  const roll = new Quaternion().setFromAxisAngle(new Vector3(0, 0, 1), -rollDeg * DEG);
  q.multiply(yaw).multiply(pitch).multiply(roll);
  return q;
}

export function createInitialState(
  scenario: Scenario,
  preset: WeatherPreset = 'CLEAR',
  timeOfDay = 10.5,
): SimState {
  const powered = scenario !== 'coldDark';
  const atRunway = scenario === 'quick' || scenario === 'demo';
  const spot = atRunway ? AIRPORT.lineupPosition : AIRPORT.gate;
  const staticY = AIRCRAFT.centerlineHeight;
  const fuelKg = 9000;
  const zfw = 60_500;
  const du = (v: number): Record<DuId, number> => ({
    pfd1: v,
    nd1: v,
    ewd: v,
    sd: v,
    nd2: v,
    pfd2: v,
    mcdu1: v,
    mcdu2: v,
    isis: v,
  });

  const s: SimState = {
    meta: {
      time: 0,
      paused: false,
      timeScale: 1,
      scenario,
      phase: powered ? (atRunway ? 'TAXI' : 'POWERED') : 'COLD_DARK',
      phaseSince: 0,
      demoActive: scenario === 'demo',
      stepCount: 0,
      lastTouchdown: null,
      crashed: false,
      assist: scenario === 'coldDark',
    },
    aircraft: {
      position: new Vector3(spot.x, staticY, spot.z),
      velocity: new Vector3(),
      acceleration: new Vector3(),
      quaternion: headingToQuaternion(spot.heading),
      p: 0,
      q: 0,
      r: 0,
      angularAccel: { p: 0, q: 0, r: 0 },
      mass: zfw + fuelKg,
      cgMac: 28,
    },
    flight: {
      ias: 0,
      tas: 0,
      gs: 0,
      mach: 0,
      aoa: 0,
      beta: 0,
      altitudeMsl: 0,
      pressureAltitude: 0,
      radioAltitude: 0,
      vs: 0,
      heading: spot.heading,
      track: spot.heading,
      pitch: 0,
      roll: 0,
      fpa: 0,
      nz: 1,
      speedTrend: 0,
      onGround: true,
      wow: [true, true, true],
      windDir: 0,
      windSpeed: 0,
      oat: 15,
      tat: 15,
      rho: 1.225,
      vls: 0,
      vaprot: 0,
      vamax: 0,
      vmax: 350,
      greenDot: 0,
      fSpeed: 0,
      sSpeed: 0,
    },
    input: { pitch: 0, roll: 0, rudder: 0, tiller: 0, brakeL: 0, brakeR: 0, owner: 'USER' },
    controls: {
      elevator: 0,
      ths: 0,
      aileronL: 0,
      aileronR: 0,
      rudder: 0,
      rudderTrim: 0,
      spoilersL: [0, 0, 0, 0, 0],
      spoilersR: [0, 0, 0, 0, 0],
      flapHandle: atRunway ? 1 : 0,
      flapConfig: atRunway ? '1+F' : '0',
      flapsAngle: atRunway ? 10 : 0,
      slatsAngle: atRunway ? 18 : 0,
      flapsTarget: atRunway ? 10 : 0,
      slatsTarget: atRunway ? 18 : 0,
      speedbrakeHandle: 0,
      spoilersArmed: atRunway,
      groundSpoilersActive: false,
      law: 'NORMAL',
      fpaRef: 0,
      pitchIntegrator: 0,
      protActive: { aoa: false, speed: false, bank: false, pitch: false },
      sidestickCapt: { x: 0, y: 0 },
      sidestickFo: { x: 0, y: 0 },
    },
    engines: [makeEngine(atRunway), makeEngine(atRunway)],
    apu: {
      master: powered && !atRunway,
      startPb: false,
      state: powered && !atRunway ? 'AVAILABLE' : 'OFF',
      n: powered && !atRunway ? 100 : 0,
      egt: powered && !atRunway ? 380 : 15,
      flap: powered && !atRunway ? 1 : 0,
      timer: 0,
      bleedPress: powered && !atRunway ? 35 : 0,
    },
    elec: {
      bat1: powered,
      bat2: powered,
      bat1V: 25.5,
      bat2V: 25.5,
      bat1Charge: 0.95,
      bat2Charge: 0.95,
      extPwrAvail: !atRunway,
      extPwrOn: false,
      gen1: true,
      gen2: true,
      apuGen: true,
      busTie: true,
      gen1Online: false,
      gen2Online: false,
      apuGenOnline: false,
      ac1Source: null,
      ac2Source: null,
      acBus1: false,
      acBus2: false,
      acEss: false,
      dcBus1: false,
      dcBus2: false,
      dcEss: false,
      dcBat: false,
      hotBus: true,
      loads: { load1: 0, load2: 0, apuLoad: 0 },
    },
    hyd: {
      green: { pressure: atRunway ? 3000 : 0, quantity: 0.95 },
      blue: { pressure: atRunway ? 3000 : 0, quantity: 0.95 },
      yellow: { pressure: atRunway ? 3000 : 0, quantity: 0.95 },
      eng1Pump: true,
      eng2Pump: true,
      elecPump: true,
      yellowElecPump: false,
      ptu: true,
      ptuActive: false,
    },
    fuel: {
      left: fuelKg * 0.38,
      right: fuelKg * 0.38,
      center: fuelKg * 0.24,
      pumps: { l1: powered, l2: powered, c1: powered, c2: powered, r1: powered, r2: powered },
      xfeed: false,
      used1: 0,
      used2: 0,
      fob: fuelKg,
    },
    pneu: {
      eng1Bleed: true,
      eng2Bleed: true,
      apuBleed: powered && !atRunway,
      xbleed: 'AUTO',
      xbleedOpen: false,
      pack1: powered,
      pack2: powered,
      packFlow: 'NORM',
      ductL: 0,
      ductR: 0,
      pack1Flow: 0,
      pack2Flow: 0,
      cabinTemp: 24,
    },
    press: {
      cabinAlt: 0,
      cabinVs: 0,
      deltaP: 0,
      modeMan: false,
      manVs: 0,
      ditching: false,
      outflowValve: 1,
      landingElev: 0,
    },
    antiIce: {
      wing: false,
      eng1: false,
      eng2: false,
      probe: false,
      iceAccretion: 0,
      engineIce: [0, 0],
      iceDetected: false,
    },
    adirs: {
      ir: [0, 1, 2].map((): SimState['adirs']['ir'][number] => ({
        mode: powered ? 'NAV' : 'OFF',
        alignRemaining: 0,
        aligned: powered,
        attAvail: powered,
      })),
      fastAlign: true,
    },
    gear: {
      lever: 'DOWN',
      position: [1, 1, 1],
      doors: [0, 0, 0],
      downLocked: [true, true, true],
      upLocked: [false, false, false],
      compression: [0.15, 0.15, 0.15],
      wheelSpin: [0, 0, 0],
      wheelAngle: [0, 0, 0],
      steerAngle: 0,
      parkingBrake: !atRunway,
      autobrake: atRunway ? 'MAX' : 'OFF',
      autobrakeActive: false,
      autobrakeDecel: false,
      brakeTemp: [60, 60],
      brakePressL: 0,
      brakePressR: 0,
      antiSkid: true,
    },
    lights: {
      strobe: atRunway ? 'ON' : 'AUTO',
      beacon: atRunway,
      wing: false,
      navLogo: powered,
      rwyTurnoff: atRunway,
      landL: atRunway ? 'ON' : 'RETRACT',
      landR: atRunway ? 'ON' : 'RETRACT',
      nose: atRunway ? 'TO' : 'OFF',
      dome: powered ? 'DIM' : 'OFF',
      annun: 'BRT',
      integral: 0.6,
      flood: 0.3,
      seatBelts: powered ? 'ON' : 'OFF',
      noSmoking: 'AUTO',
      strobeOn: false,
      beaconOn: 0,
      landingLightExtension: atRunway ? [1, 1] : [0, 0],
      duBrightness: du(0.85),
    },
    warnings: {
      masterWarning: false,
      masterCaution: false,
      messages: [],
      acknowledged: [],
      cleared: [],
      memos: [],
      toConfigTest: 0,
      fireTest: false,
    },
    ecam: { sdPage: atRunway ? 'WHEEL' : 'DOOR', manualPage: null },
    efis: [makeEfis(), makeEfis()],
    fcu: {
      spd: 150,
      mach: 0.78,
      spdMach: 'SPD',
      spdManaged: true,
      hdg: spot.heading,
      hdgManaged: true,
      hdgPreset: false,
      trkFpa: false,
      alt: atRunway ? DEFAULT_CRZ_FL * 100 : 5000,
      altInc: 1000,
      vs: 0,
      fpa: 0,
      vsDashes: true,
      metric: false,
      exped: false,
      knobAnim: { spd: 0, hdg: 0, alt: 0, vs: 0 },
    },
    afs: {
      ap1: false,
      ap2: false,
      fd1: true,
      fd2: true,
      athrArmed: false,
      athrActive: false,
      athrMode: null,
      athrArmedMode: null,
      lateral: null,
      lateralArmed: atRunway ? 'NAV' : null,
      vertical: null,
      verticalArmed: [],
      approachCap: null,
      apprArmed: false,
      locArmed: false,
      fdRoll: 0,
      fdPitch: 0,
      fdYaw: 0,
      targetSpeed: 150,
      targetMach: 0.78,
      targetAltitude: 0,
      phase: 'PREFLIGHT',
      v1: 138,
      vr: 142,
      v2: 146,
      flexTemp: 48,
      thrRedAlt: 1500,
      accAlt: 1500,
      transAlt: 11000,
      vapp: 138,
      modeChangeTime: { athr: -99, lat: -99, vert: -99, cap: -99, ap: -99 },
      speedIntegrator: 0,
      altCaptureVs: 0,
      flareStartVs: 0,
      retardCalled: false,
      alphaFloor: false,
      apDisconnectWarning: 0,
      athrDisconnectCaution: 0,
    },
    fplan: {
      origin: AIRPORT.icao,
      originRwy: '27',
      destination: AIRPORT.icao,
      destRwy: '27',
      waypoints: atRunway ? DEFAULT_ROUTE.map((w) => ({ ...w })) : [],
      activeLeg: 1,
      crzFl: DEFAULT_CRZ_FL,
      costIndex: 30,
      flightNo: 'HAO320',
      zfw: zfw / 1000,
      blockFuel: fuelKg / 1000,
      initialized: atRunway,
      perfInitialized: atRunway,
      distToDest: 0,
      distToWpt: 0,
      todDist: 0,
      xtk: 0,
      desiredTrack: 270,
      directToPending: null,
    },
    ils: {
      ident: 'IHAO',
      freq: 109.5,
      course: 270,
      tuned: atRunway,
      locValid: false,
      gsValid: false,
      locDev: 0,
      gsDev: 0,
      dme: 0,
      markerOuter: false,
    },
    mcdu: [makeMcdu(), makeMcdu()],
    weather: makeWeather(preset, timeOfDay),
    failures: {
      eng1Fail: false,
      eng2Fail: false,
      gen1Fail: false,
      hydGreenLeak: false,
      apuFail: false,
    },
    mech: { engMode: 'NORM', guardsOpen: [] },
    doors: {
      cabinFwdL: atRunway ? 0 : 1,
      cabinFwdR: 0,
      cabinAftL: 0,
      cabinAftR: 0,
      cargoFwd: atRunway ? 0 : 1,
      cargoAft: atRunway ? 0 : 1,
      avionics: 0,
    },
    radio: { vor1: 'HAO', vor2: 'NTH' },
  };
  s.fplan.distToDest = 0;
  if (!powered) {
    s.lights.duBrightness = du(0.85); // 旋鈕位置保持，但無電源時顯示器黑屏
    s.elec.hotBus = true;
  }
  return s;
}
