/**
 * Hreflang Configuration BDD Tests - SEO Phase 2A-3
 *
 * BDD 測試：驗證 Hreflang 配置正確性
 *
 * 測試策略：
 * - 🔴 sitemap.xml 不應該包含 hreflang="en"（應用沒有英文版本）
 * - 🔴 sitemap.xml 應該只有 zh-TW 和 x-default
 * - 🔴 SEOHelmet fallback alternates 不應該包含英文 locale
 * - 🔴 SEOHelmet 不應該為單一語言生成 og:locale:alternate
 *
 * [fix:2025-12-31] sitemap.xml 現在由 vite-ssg-sitemap 在 build 時自動生成到 dist/
 * 測試改為驗證 SEOHelmet 配置正確性（sitemap 驗證移至 CI pipeline）
 *
 * 參考：fix/seo-phase2a-bdd-approach
 * 依據：[SEO 審查報告 2025-11-25] Hreflang 配置錯誤問題
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

describe('Hreflang Configuration (BDD)', () => {
  describe('🔴 RED: sitemap.xml Hreflang 配置', () => {
    // sitemap.xml is auto-generated by vite-ssg-sitemap; hreflang provided via SEOHelmet
    // 這些測試驗證 sitemap.xml 不包含錯誤的 hreflang 配置
    const distSitemapPath = resolve(__dirname, '../dist/sitemap.xml');
    const sitemapExists = existsSync(distSitemapPath);

    // 檢查是否為正確的 ratewise build（URL 應包含 /ratewise/）
    const isRatewiseBuild =
      sitemapExists && readFileSync(distSitemapPath, 'utf-8').includes('haotool.org/ratewise/');

    it('should NOT contain hreflang="en" (no English version exists)', () => {
      if (!sitemapExists || !isRatewiseBuild) {
        // sitemap 在 build 時生成，跳過此測試
        console.log('⏭️ Skipping: ratewise sitemap.xml not found (generated during build)');
        return;
      }
      const sitemapContent = readFileSync(distSitemapPath, 'utf-8');
      // 🔴 紅燈：sitemap.xml 不應該包含英文 hreflang
      expect(sitemapContent).not.toContain('hreflang="en"');
    });

    it('should only have zh-TW and x-default hreflang if present', () => {
      if (!sitemapExists || !isRatewiseBuild) {
        console.log('⏭️ Skipping: ratewise sitemap.xml not found (generated during build)');
        return;
      }
      const sitemapContent = readFileSync(distSitemapPath, 'utf-8');

      // vite-ssg-sitemap doesn't generate hreflang by default
      const hasHreflang = sitemapContent.includes('hreflang=');
      if (hasHreflang) {
        expect(sitemapContent).toContain('hreflang="zh-TW"');
        expect(sitemapContent).toContain('hreflang="x-default"');

        // 確認沒有其他語言（en, ja, ko, etc.）
        expect(sitemapContent).not.toContain('hreflang="en"');
        expect(sitemapContent).not.toContain('hreflang="ja"');
        expect(sitemapContent).not.toContain('hreflang="ko"');
        expect(sitemapContent).not.toContain('hreflang="zh-CN"');
      } else {
        // 沒有 hreflang 也是可接受的（hreflang 由 HTML meta tags 提供）
        console.log('ℹ️ sitemap.xml 不包含 hreflang（由 HTML meta tags 提供）');
      }
    });

    it('should have correct xhtml:link elements if hreflang is present', () => {
      if (!sitemapExists || !isRatewiseBuild) {
        console.log('⏭️ Skipping: ratewise sitemap.xml not found (generated during build)');
        return;
      }
      const sitemapContent = readFileSync(distSitemapPath, 'utf-8');

      // vite-ssg-sitemap doesn't generate xhtml:link by default
      const xlinkMatches = sitemapContent.match(/<xhtml:link/g);
      if (xlinkMatches) {
        // 如果有 xhtml:link，檢查數量正確
        // 20 條 URL * 2 語言 = 40
        expect(xlinkMatches.length).toBe(40);
      } else {
        // 沒有 xhtml:link 也是可接受的（hreflang 由 HTML meta tags 提供）
        console.log('ℹ️ sitemap.xml 不包含 xhtml:link（由 HTML meta tags 提供）');
      }
    });
  });

  describe('🔴 RED: SEOHelmet.tsx Hreflang 配置', () => {
    const seoHelmetPath = resolve(__dirname, 'components/SEOHelmet.tsx');
    const seoHelmetContent = readFileSync(seoHelmetPath, 'utf-8');

    it('should NOT have English locale in fallback alternates', () => {
      // 🔴 紅燈：fallback alternates 不應該包含英文
      const alternatesMatch = /const alternatesToRender[\s\S]*?\[[\s\S]*?\];/.exec(
        seoHelmetContent,
      );
      expect(alternatesMatch).toBeTruthy();

      const alternatesBlock = alternatesMatch![0];

      // 確認不包含 'en', 'en-US', 'en-GB' 等英文 locale
      expect(alternatesBlock).not.toContain("'en'");
      expect(alternatesBlock).not.toContain('"en"');
      expect(alternatesBlock).not.toContain("'en-US'");
      expect(alternatesBlock).not.toContain('"en-US"');
      expect(alternatesBlock).not.toContain("'en-GB'");
      expect(alternatesBlock).not.toContain('"en-GB"');
    });

    it('should only have x-default and DEFAULT_LOCALE in fallback alternates', () => {
      // 🔴 紅燈：確認 fallback alternates 只有 x-default 和 DEFAULT_LOCALE
      const alternatesMatch = /const alternatesToRender[\s\S]*?\[[\s\S]*?\];/.exec(
        seoHelmetContent,
      );
      expect(alternatesMatch).toBeTruthy();

      const alternatesBlock = alternatesMatch![0];

      // 應該包含 x-default 和 DEFAULT_LOCALE
      expect(alternatesBlock).toMatch(/'x-default'|"x-default"/);
      expect(alternatesBlock).toMatch(/DEFAULT_LOCALE/);

      // 計算 hrefLang 的數量（應該只有 2 個）
      const hrefLangMatches = alternatesBlock.match(/hrefLang:/g);
      expect(hrefLangMatches?.length).toBe(2);
    });

    it('should not generate og:locale:alternate for the same locale as og:locale', () => {
      // 🔴 紅燈：檢查 og:locale:alternate 生成邏輯
      // 當只有一種語言時，不應該生成 og:locale:alternate

      // 搜尋 og:locale:alternate 生成代碼
      const ogLocaleAlternateMatch = /<meta[\s\S]*?property="og:locale:alternate"[\s\S]*?\/>/.exec(
        seoHelmetContent,
      );

      // 如果找到 og:locale:alternate，確認有 filter 邏輯排除主要 locale
      if (ogLocaleAlternateMatch) {
        // 檢查是否有過濾邏輯（filter 掉 x-default）
        expect(seoHelmetContent).toContain("hrefLang !== 'x-default'");

        // 檢查是否有過濾主要 locale 的邏輯
        // 當 alternates 只有 x-default 和主要 locale 時，應該不生成 og:locale:alternate
        const filterLogic = /normalizedAlternates[\s\S]*?\.filter[\s\S]*?\.map/.exec(
          seoHelmetContent,
        );
        expect(filterLogic).toBeTruthy();
      }
    });
  });

  describe('🔴 RED: Hreflang 最佳實踐驗證', () => {
    it('sitemap.xml and SEOHelmet should have consistent hreflang configuration', () => {
      // Validate SEOHelmet's HTML meta tag hreflang configuration

      const seoHelmetPath = resolve(__dirname, 'components/SEOHelmet.tsx');
      const seoHelmetContent = readFileSync(seoHelmetPath, 'utf-8');

      // SEOHelmet 應該只有 x-default 和 zh-TW
      expect(seoHelmetContent).toMatch(/hrefLang:\s*DEFAULT_LOCALE/);
      expect(seoHelmetContent).toMatch(/hrefLang:\s*['"]x-default['"]/);

      // SEOHelmet 不應該有 en
      expect(seoHelmetContent).not.toContain("'en'");
      expect(seoHelmetContent).not.toContain('"en"');

      // sitemap.xml hreflang validation moved to CI pipeline
    });

    it('should follow hreflang best practices: no self-referencing alternate', () => {
      // 🔴 紅燈：Hreflang 最佳實踐 - 主要語言不應該作為 alternate

      const seoHelmetPath = resolve(__dirname, 'components/SEOHelmet.tsx');
      const seoHelmetContent = readFileSync(seoHelmetPath, 'utf-8');

      // 檢查是否有邏輯避免主要 locale 成為 og:locale:alternate
      // 當只有一種語言時，應該：
      // - og:locale = zh_TW (主要語言)
      // - 不應該有 og:locale:alternate = zh_TW

      // Filter x-default and locales matching primary locale
      // 1. hrefLang === 'x-default'
      // 2. hrefLang.replace('-', '_') === ogLocale（主要語言）

      // 查找過濾掉與主要 locale 相同項目的邏輯
      const filterPattern = /hrefLang\.replace\(['"]-['"],\s*['"]_['"]\)\s*!==\s*ogLocale/;
      const hasOgLocaleFilter = filterPattern.test(seoHelmetContent);

      // 應該過濾掉與主要 locale 相同的項目
      expect(hasOgLocaleFilter).toBe(true);

      // 確認也有過濾 x-default
      expect(seoHelmetContent).toContain("hrefLang !== 'x-default'");
    });
  });
});
